[build]
  command = "npm run build && npm run export"
  publish = "out"
  functions = './functions/'
[[redirects]]
  from = "/api/subscribe"
  to = "/.netlify/functions/:splat"
  status = 200
  query = {path = ":path"} #  apply this rule for /old-path?path=example
